# api/main.py
"""
FastAPI application — the HTTP entry point for the Clinical Trial Matcher.

Endpoints:
    POST /query   — Main query endpoint (guarded + routed)
    GET  /health  — Liveness probe
    GET  /docs    — Swagger UI (auto-generated by FastAPI)

Start locally:
    uvicorn api.main:app --reload --port 8000
"""

import logging
import uuid

import config  # noqa: F401 — configures logging on import
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from api.schemas import BlockedResponse, QueryRequest, QueryResponse, TrialResult
from guardrails.guard import check_guardrails
from pipeline.planner import plan
from pipeline.responder import respond
from pipeline.graph import pipeline

logger = logging.getLogger(__name__)

app = FastAPI(
    title="Clinical Trial Matcher API",
    description=(
        "AI-powered patient-to-trial matching. "
        "Guarded by topic-scoping guardrails, routed by a Planner node."
    ),
    version="2.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # tighten in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Health ──────────────────────────────────────────────────────────────────

@app.get("/health", tags=["system"])
def health():
    return {"status": "ok", "service": "clinical-trial-matcher"}


# ── Main query endpoint ─────────────────────────────────────────────────────

@app.post(
    "/query",
    response_model=QueryResponse,
    responses={400: {"model": BlockedResponse, "description": "Guardrails blocked the request"}},
    tags=["query"],
    summary="Query the clinical trial matcher",
)
def query(request: QueryRequest):
    """
    Main entry point for all user queries.

    Flow:
        1. NeMo-style Guardrails check (keyword hard-block + LLM topic classifier)
        2. Planner routes to "conversational" or "technical"
        3. Conversational → Responder (multi-turn LLM answer with MemorySaver context)
           Technical      → Full pipeline (extract → fetch → ingest → retrieve → score)
    """
    # Determine effective query text for guardrail check
    query_text = request.text_query or ""
    if not query_text and not request.pdf_path:
        raise HTTPException(
            status_code=422,
            detail="Provide either text_query or pdf_path.",
        )

    # ── Step 1: Guardrails ──────────────────────────────────────────────
    if query_text:
        blocked, reason = check_guardrails(query_text)
        if blocked:
            logger.warning("api.guardrail_block reason=%s", reason)
            raise HTTPException(status_code=400, detail=reason)

    # ── Step 2: Session ID ──────────────────────────────────────────────
    session_id = request.session_id or str(uuid.uuid4())

    # ── Step 3: Planner routing ─────────────────────────────────────────
    has_pdf = bool(request.pdf_path)
    route = plan(query_text, has_pdf=has_pdf)
    logger.info("api.route session=%s route=%s", session_id, route)

    # ── Step 4a: Conversational path ────────────────────────────────────
    if route == "conversational":
        answer = respond(
            user_message=query_text,
            conversation_history=None,   # MemorySaver history injected in future
        )
        return QueryResponse(
            route="conversational",
            session_id=session_id,
            answer=answer,
        )

    # ── Step 4b: Technical path (full pipeline) ─────────────────────────
    if not request.pdf_path:
        raise HTTPException(
            status_code=422,
            detail="Technical route requires a pdf_path. Please upload a patient PDF.",
        )

    result = pipeline.invoke(
        {
            "pdf_path": request.pdf_path,
            "raw_text": None,
            "patient_profile": None,
            "fetched_trials": None,
            "chunks_stored": None,
            "retrieved_chunks": None,
            "scored_trials": None,
            "error": None,
            "retry_count": 0,
            "session_id": session_id,
            "conversation_history": None,
        },
        config={"configurable": {"thread_id": session_id}},
    )

    if result.get("error"):
        raise HTTPException(status_code=500, detail=result["error"])

    trials = [TrialResult(**t) for t in (result.get("scored_trials") or [])]
    profile_data = None
    if result.get("patient_profile"):
        profile_data = result["patient_profile"].model_dump()

    return QueryResponse(
        route="technical",
        session_id=session_id,
        trials=trials,
        patient_profile=profile_data,
    )
